# Generated by Django 2.2.7 on 2019-11-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_m', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='City',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
